Refactor for User Service
EPS-DataMed/user-service pull request #4
Opened 2024-06-13 01:40 UTC by vitordiniz25

Use new data model for users, doctors and dependents

2024-06-13 02:37 UTC, VictorAmaralC requested changes

2024-06-13 02:37 UTC, VictorAmaralC commented on app/routers/doctor.py
Remover rota de criação de médicos (POST), rota será transferida para o repositório de autenticação

2024-06-13 02:37 UTC, VictorAmaralC commented on app/routers/user.py
Remover rota de criação de usuário (POST), rota será transferida para o repositório de autenticação

2024-06-15 15:16 UTC, lucasgabriel-2 approved these changes

2024-06-15 15:16 UTC, merged